### ISSUE TITLE
Latest release does not run (Apple Intel)

### ISSUE THREAD

**Issue by L-Ryland** [IcyStudio/TeleGPT#16]
Here's the output whern I try to execute the command

```shell
❯ ./telegpt
zsh: bad CPU type in executable: ./telegpt
```

**Comment by unixzii** [comment]
Hi @L-Ryland, we didn't build the x86_64 architecture in our latest release. We will build it and update the release later, please hold tight.

**Comment by unixzii** [comment]
The x86_64 binary is released! Please check out here: https://github.com/Helixform/TeleGPT/releases/tag/v0.1.1
